### ISSUE TITLE
无法运行 提示缺少动态链接库

### ISSUE THREAD

**Issue by wolskiCN** [RaySky-Rt/Echo-Live-Typetool#2]
![XZ`Z`0YN291~9HUMP{8ULX](https://github.com/RaySky-Rt/Echo-Live-Typetool/assets/3684416/99cf4aaa-6a5b-4740-ab13-dc927bc7607f)
按照弹出的缺失dll提示补完还是无法使用

**Comment by RaySky-Rt** [comment]
看起来您使用的是系统是Windows7？

由于我发布的可执行文件的编译环境是Windows10，所以可能会出现与Win7不兼容的情况

这个报错应该与字符串操作部分有关系，我会尽快检查代码和我本地的编译设置并排除错误

**Comment by RaySky-Rt** [comment]
以及，我可能需要您提供更多的信息来定位错误

您提到了 “按提示补全dll文件” ，这说明在此之前应该还出现过不同的报错信息，如果您还记得的话，可以列出先前提示缺失的dll文件吗？

**Comment by wolskiCN** [comment]
![TNTPX61Y{4L0CACQJDFLH4](https://github.com/RaySky-Rt/Echo-Live-Typetool/assets/3684416/d99c6767-b595-4ab4-aa4e-f1a634bf45ef)
提示缺失的是这些，以及，瘟11

**Comment by RaySky-Rt** [comment]
win11...？建议你尝试一下安装 [Visual C++ Redistributable](https://aka.ms/vs/17/release/vc_redist.x64.exe) 包，可能会解决问题

**Comment by RaySky-Rt** [comment]
不过程序的兼容性问题确实是我没有考虑到的点，我预计会在下个版本中改善兼容性

**Comment by wolskiCN** [comment]
安装C++运行包了，重启，移除dll，还是会提示找不到dll

**Comment by RaySky-Rt** [comment]
这个问题应该是由于我用MinGW编译的时候用了动态链接库，而你的电脑上没有对应的库
我把程序重新用静态链接库的方式编译了一份，应该可以正常运行了 [Typetool v0.5-a1 alpha](https://github.com/RaySky-Rt/Echo-Live-Typetool/releases/tag/V0.5-a1)
